# data config
data_path: data/train.txt
# model config
batch_size: 64
block_size: 256
vocab_size: 7587
n_layer: 12
n_head: 12
n_embd: 768
dropout: 0.0
bias: True
# training config
max_epoch : 1919810
tensorboard_path :  ./tensorboard
device: cuda
# AdamW optimizer
lr :  1e-4
weight_decay : 1e-1
beta1: 0.9
beta2: 0.95
# checkpoint config
checkpoint_root: ./checkpoints
save_freq: 4000 # save when global_step % save_freq == 0
resume_from: checkpoints/cpt56000.pth
# other config
seed :  114514
